export const aidTexts = {
  title: "Zakres pomocy i wsparcia",
  list1: "Zaburzenia nastroju (depresja)",
  list2: "Zaburzenia lękowe",
  list3: "Kryzysy w związku lub małżeństwie",
  list4: "Kryzys emocjonalny",
  list5: "Stres oraz napięcia emocjonalne",
  list6: "Trudności w relacjach",
  list7: "Trudności w macierzyństwie",
  list71: "(w tym: przygotowanie się do macierzyństwa, depresja poporodowa)",
  list8: "Trudności w podejmowaniu decyzji",
  list9: "Trudności w stawianiu granic (brak asertywności)",
  list10: "Poczucie zagubienia",
  list11: "Niskie poczucie własnej wartości",
};
